### ISSUE TITLE
Authentication with CLI causes panic

### ISSUE THREAD

**Issue by whitep4nth3r** [sailhouse/cli#1]
Steps to reproduce:

1. Install CLI with `brew`
2. run `sailhouse auth`
3. Observe output as below:

```
Authenticated!
panic: open /Users/salma/.sailhouse/profile.toml: no such file or directory

goroutine 1 [running]:
github.com/sailhouse/sailhouse/config.(*Profile).SaveProfile(0x101322f20?)
	/home/runner/work/cli/cli/config/profile.go:50 +0xc8
github.com/sailhouse/sailhouse/config.LoadProfile()
	/home/runner/work/cli/cli/config/profile.go:25 +0xc8
github.com/sailhouse/sailhouse/cmd.init.1.func1(0x140003ed800?, {0x101152751?, 0x0?, 0x0?})
	/home/runner/work/cli/cli/cmd/auth.go:61 +0x4d8
github.com/spf13/cobra.(*Command).execute(0x140003ed800, {0x101690ad8, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x10164f760)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/sailhouse/sailhouse/cmd.Execute({0x10123294c?, 0x140000021a0?})
	/home/runner/work/cli/cli/cmd/root.go:66 +0x52c
main.main()
	/home/runner/work/cli/cli/main.go:20 +0x70
```

**Comment by estephinson** [comment]
Closed with release [v0.2.9](https://github.com/sailhouse/cli/releases/tag/v0.2.9)
